# Generated by Django 5.2.4 on 2025-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_created_at_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='time_required',
            field=models.CharField(default='1 day', max_length=100),
        ),
    ]
