# Generated by Django 5.2.4 on 2025-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_assigned_to_task_time_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_required',
            field=models.CharField(max_length=100),
        ),
    ]
