# Generated by Django 4.2.11 on 2025-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_due_time_alter_task_time_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(blank=True, default='Unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_required',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
