# Generated by Django 5.2.8 on 2025-12-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_options_task_status_task_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_required',
            field=models.CharField(max_length=100),
        ),
    ]
