# Generated by Django 4.2.11 on 2025-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_task_options_task_status_task_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overtime_hours',
            field=models.IntegerField(default=0, help_text='Additional hours if needed'),
        ),
        migrations.AddField(
            model_name='task',
            name='overtime_minutes',
            field=models.IntegerField(default=0, help_text='Additional minutes if needed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
